##########################################
####  Get processing extent
##########################################
#### | Project name: Atra climate
#### | Script type: Data processing
#### | What it does: Creates processing extent that will be used to process and
####  constrain data further in the process. It is generated by using the rectangular extent
####  of all ecoregions in which Salamandra atra points are found.
#### | Creator: ---
#### | Contact: ---
##########################################


# Script setup ------------------------------------------------------------

pacman::p_load(Rahat, tidyverse, janitor, sf, raster, mapview, fasterize)

# Load setup script. Fork is for type of computer, in case here::here() cannot
# find the path on the local folder. This is the case on the computing cluster,
# where here doesn't work well.

source(here::here("R", "main_setup.R"))
  

########################################
##### Determine processing extent


#### Load wwf ecoregions
## Set path for ecoregions geopackage file
# variable folder_path_data_misc comes from main_setup
wwf_out <- str_glue("{folder_path_data_misc}/wwf_terr_ecos.gpkg")

## Run fork to convert to geopackage if file don't exists. 
if (!file.exists(wwf_out))
{
  olsen_data <- "Data_RAW/official_teow/official/wwf_terr_ecos.shp" %>% 
    milkunize2("archive") %>% 
    st_read()
  
  st_write(olsen_data, wwf_out)
} else {
  olsen_data <- st_read(wwf_out)
}

#### Create raster ####
# Create raster with 0.1 degree resolution for ecoregion data
xy <- matrix(rep(1, 259200), 360 * 5, 720 * 5)

# Turn the matrix into a raster
rast <- raster(xy)
# Set extent and coordinate system to wgs84
extent(rast) <- c(-180, 180, -90, 90)
projection(rast) <- CRS("+proj=longlat +datum=WGS84")
# Convert to raster
ecozones_raster <- fasterize(olsen_data, rast, field = "ECO_ID")

#### Load species data ####
# Load Salamandra atra species

data_atra_all_sp <- var_path_species_data %>% 
  st_read()

# Extract point values from raster 
sp_ecozones <- raster::extract(ecozones_raster, data_atra_all_sp, sp = TRUE)

# Get ecozones where atra lives
my_obj <- olsen_data %>% 
  filter(ECO_ID %in% unique(sp_ecozones$layer))


#### This could be the final processing extent 
spatial_extent <- my_obj %>% 
  st_bbox() %>% 
  st_as_sfc()

## Save spatial extent 
# Spatial extent referes to the rectangular bounding box for the species
st_write(spatial_extent, str_glue("{folder_path_data_species}/atra_spatial_extent.gpkg"))

## Save econozes
# Ecozones where atra lives
st_write(my_obj, str_glue("{folder_path_data_misc}/atra_ecozones.gpkg"))



# Create a figure for processing extent -----------------------------------
utm_33n <- "+proj=utm +zone=33 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"


dinaric_countries <- "/Projects/atra_data/Data/procext_countries.gpkg" %>% 
  st_read()# %>% 

my_countries <- rnaturalearthdata::countries50 %>% 
  st_as_sf()

plot_processing_extent <- ggplot() +
  # geom_sf(data = dinaric_countries) +
  geom_sf(data = my_countries, fill = "grey90") +
  geom_sf(data = my_obj, aes(fill = ECO_NAME), alpha = 0.5) +
  geom_sf(data = spatial_extent, fill = NA, linetype = "dashed", size = 1) +
  geom_sf(data = data_atra_all_sp, size = 0.25, color = "grey10", alpha = 0.95) +
  coord_sf(xlim = c(st_bbox(spatial_extent)[1], 
                    st_bbox(spatial_extent)[3]),
           ylim = c(st_bbox(spatial_extent)[2],
                    st_bbox(spatial_extent)[4])) +
  labs(
    fill = "Ecoregion name:"
  ) +
  scale_fill_viridis_d(direction = -1) +
  theme_void() +
  theme(
    legend.position = "top",
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 14, face = "bold"),
  )


map_outname_procext <- here("results", "figure", "map_processing_extent.png")


ggsave(map_outname_procext, plot_processing_extent,
       dpi = 300, height = 9.5, width = 11)


